#!/usr/bin/php
<?php
	$app = count($argv) < 2 ? "VScout" : $argv[1];
	echo "Installing $app...\n";
	
	$dir = dirname(__FILE__);

	require_once($dir . '/classes/Config-'.$app.'.php');
	require_once($dir . '/classes/data/DataFile.php');
	require_once($dir . '/classes/core/ProcessControl.php');
	require_once($dir . '/classes/utils/TemplateParser.php');

	$source = file_get_contents("$dir/classes/" . $app . ".php");
	preg_match_all('/\s*#\[([a-zA-Z0-9_\-\/]+)\]#\s*/', $source, $parts, PREG_SET_ORDER);
	foreach ($parts as $part) 
	{
		$source = str_replace(trim($part[0]), preg_replace('/<\?php\s*(.*)/m', '$1', file_get_contents($dir . '/classes/' . $part[1] . '.php')), $source);
	}
	file_put_contents(BIN_DIR . "/" . NAME, $source);
	system("chmod +x " . BIN_DIR . "/" . NAME);

	function cprecursive($src, $dst) 
	{
	    $dir = opendir($src);
	    @mkdir($dst);

	    while (false !== ($file = readdir($dir))) 
	    {
	        if (in_array($file, ['.','..']))
	        	continue; 

            if (is_dir($src . '/' . $file))  cprecursive($src . '/' . $file, $dst . '/' . $file);
            else                             copy($src . '/' . $file, $dst . '/' . $file);
	    }
	    closedir($dir);
	}
	
	cprecursive("$dir/data", DATA_DIR . '/');
	system(BIN_DIR . "/" . NAME . ' install');
